<a href="https://colab.research.google.com/github/Viny2030/UMSA-Analisis_de_datos/blob/main/ba_ci_001_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img src="https://pypi.org/static/images/logo-small.8998e9d1.svg" width="" height="">
</p>

 # **<font color="#07a8ed">Preprocesamiento de los Datos - Codificación e imputaciones</font>**

## **<font color="#07a8ed">Bibliotecas**

### **<font color="#07a8ed">Para análisis de datos**

In [ ]:
import pandas as pd
import numpy as np

### **<font color="#07a8ed">Para preprocesamiento de datos**

In [ ]:
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

 ## **<font color="#07a8ed">Obtención de los Datos</font>**

In [ ]:
url = "https://raw.githubusercontent.com/cristiandarioortegayubro/BA/main/Datasets/banco.csv"

In [ ]:
analisis = pd.read_csv(url, index_col=0)
analisis.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may       261         1     -1         0  unknown      no  
1  unknown    5   may       151         1     -1         0  unknown      no  
2  unknown    5   may        76         1     -1         0  unknown      no  
3  unknown    5   may        92         1     -1         0  unknown      no  
4  unknown    5   may       198         1     -1         0  unknown      no

In [ ]:
# analisis.to_csv("bank-full.csv")

 ## **<font color="#07a8ed">Análisis Exploratorio de los Datos</font>**

 ### **<font color="#07a8ed">Información inicial de las variables</font>**

In [ ]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  deposit    45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 6.2+ MB


 ### **<font color="#07a8ed">Valores únicos por variable</font>**

In [ ]:
analisis.age.unique()

array([58, 44, 33, 47, 35, 28, 42, 43, 41, 29, 53, 57, 51, 45, 60, 56, 32,
       25, 40, 39, 52, 46, 36, 49, 59, 37, 50, 54, 55, 48, 24, 38, 31, 30,
       27, 34, 23, 26, 61, 22, 21, 20, 66, 62, 83, 75, 67, 70, 65, 68, 64,
       69, 72, 71, 19, 76, 85, 63, 90, 82, 73, 74, 78, 80, 94, 79, 77, 86,
       95, 81, 18, 89, 84, 87, 92, 93, 88])

In [ ]:
analisis.job.unique()

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

In [ ]:
analisis.marital.unique()

array(['married', 'single', 'divorced'], dtype=object)

In [ ]:
analisis.education.unique()

array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object)

In [ ]:
analisis.default.unique()

array(['no', 'yes'], dtype=object)

In [ ]:
analisis.balance.unique()

array([ 2143,    29,     2, ...,  8205, 14204, 16353])

In [ ]:
analisis.housing.unique()

array(['yes', 'no'], dtype=object)

In [ ]:
analisis.loan.unique()

array(['no', 'yes'], dtype=object)

In [ ]:
analisis.contact.unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [ ]:
analisis.day.unique()

array([ 5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 19, 20, 21, 23, 26, 27, 28,
       29, 30,  2,  3,  4, 11, 17, 18, 24, 25,  1, 10, 22, 31])

In [ ]:
analisis.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [ ]:
analisis.duration.unique()

array([ 261,  151,   76, ..., 1298, 1246, 1556])

In [ ]:
analisis.campaign.unique()

array([ 1,  2,  3,  5,  4,  6,  7,  8,  9, 10, 11, 12, 13, 19, 14, 24, 16,
       32, 18, 22, 15, 17, 25, 21, 43, 51, 63, 41, 26, 28, 55, 50, 38, 23,
       20, 29, 31, 37, 30, 46, 27, 58, 33, 35, 34, 36, 39, 44])

In [ ]:
analisis.pdays.unique()

array([ -1, 151, 166,  91,  86, 143, 147,  89, 140, 176, 101, 174, 170,
       167, 195, 165, 129, 188, 196, 172, 118, 119, 104, 171, 117, 164,
       132, 131, 123, 159, 186, 111, 115, 116, 173, 178, 110, 152,  96,
       103, 150, 175, 193, 181, 185, 154, 145, 138, 126, 180, 109, 158,
       168,  97, 182, 127, 130, 194, 125, 105, 102,  26, 179,  28, 183,
       155, 112, 120, 137, 124, 187, 190, 113, 162, 134, 169, 189,   8,
       144, 191, 184, 177,   5,  99, 133,  93,  92,  10, 100, 156, 198,
       106, 153, 146, 128,   7, 121, 160, 107,  90,  27, 197, 136, 139,
       122, 157, 149, 135,  30, 114,  98, 192, 163,  34,  95, 141,  31,
       199,  94, 108,  29, 268, 247, 253, 226, 244, 239, 245, 204, 231,
       238, 258, 230, 254, 265,  71, 223, 246, 250, 266, 240, 205, 261,
       259, 241, 260, 234, 251, 225, 161, 237, 262, 248, 255, 220, 227,
       206, 224, 249, 235, 228, 263,   2, 270, 232, 252, 207, 200, 269,
       233, 256, 273, 272, 242, 264, 208, 214, 222, 271, 203, 22

In [ ]:
analisis.previous.unique()

array([  0,   3,   1,   4,   2,  11,  16,   6,   5,  10,  12,   7,  18,
         9,  21,   8,  14,  15,  26,  37,  13,  25,  20,  27,  17,  23,
        38,  29,  24,  51, 275,  22,  19,  30,  58,  28,  32,  40,  55,
        35,  41])

In [ ]:
analisis.poutcome.unique()

array(['unknown', 'failure', 'other', 'success'], dtype=object)

 ## **<font color="#07a8ed">Reemplazo de "unknown"</font>**

In [ ]:
analisis.replace({"unknown": None}, inplace=True)

In [ ]:
analisis.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married       None      no     1506     yes   no   
4   33          None    single       None      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

  contact  day month  duration  campaign  pdays  previous poutcome deposit  
0    None    5   may       261         1     -1         0     None      no  
1    None    5   may       151         1     -1         0     None      no  
2    None    5   may        76         1     -1         0     None      no  
3    None    5   may        92         1     -1         0     None      no  
4    None    5   may       198         1     -1         0     None      no  
5    None    5   may       139         1     -1         0     None      no  
6    None    5   may       217         1     -1         0     None      no  
7    None    5   may       380         1     -1         0     None      no  
8    None    5   may        50         1     -1         0     None      no  
9    None    5   may        55         1     -1         0     None      no

In [ ]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        44923 non-null  object
 2   marital    45211 non-null  object
 3   education  43354 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    32191 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   8252 non-null   object
 16  deposit    45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 6.2+ MB


In [ ]:
analisis.isnull().sum().sort_values(ascending=False)

poutcome     36959
contact      13020
education     1857
job            288
month            0
previous         0
pdays            0
campaign         0
duration         0
age              0
day              0
loan             0
housing          0
balance          0
default          0
marital          0
deposit          0
dtype: int64

 ## **<font color="#07a8ed">Codificación de variables categóricas</font>**

Las columnas a convertir string con LabelEncoder son:
- job
- marital
- education
- default
- housing
- loan
- contact
- poutcome


In [ ]:
convertir = LabelEncoder()

In [ ]:
analisis.insert(2,column="numjob",value=convertir.fit_transform(analisis.job))
analisis.insert(4,column="nummarital",value=convertir.fit_transform(analisis.marital))
analisis.insert(6,column="numeducation",value=convertir.fit_transform(analisis.education))
analisis.insert(8,column="numdefault",value=convertir.fit_transform(analisis.default))
analisis.insert(11,column="numhousing",value=convertir.fit_transform(analisis.housing))
analisis.insert(13,column="numloan",value=convertir.fit_transform(analisis.loan))
analisis.insert(15,column="numcontact",value=convertir.fit_transform(analisis.contact))
analisis.insert(23,column="numpoutcome",value=convertir.fit_transform(analisis.poutcome))

In [ ]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45211 entries, 0 to 45210
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   age           45211 non-null  int64 
 1   job           44923 non-null  object
 2   numjob        45211 non-null  int64 
 3   marital       45211 non-null  object
 4   nummarital    45211 non-null  int64 
 5   education     43354 non-null  object
 6   numeducation  45211 non-null  int64 
 7   default       45211 non-null  object
 8   numdefault    45211 non-null  int64 
 9   balance       45211 non-null  int64 
 10  housing       45211 non-null  object
 11  numhousing    45211 non-null  int64 
 12  loan          45211 non-null  object
 13  numloan       45211 non-null  int64 
 14  contact       32191 non-null  object
 15  numcontact    45211 non-null  int64 
 16  day           45211 non-null  int64 
 17  month         45211 non-null  object
 18  duration      45211 non-null  int64 
 19  camp

In [ ]:
analisis.head(10)

age           job  numjob   marital  nummarital  education  numeducation  \
0   58    management       4   married           1   tertiary             2   
1   44    technician       9    single           2  secondary             1   
2   33  entrepreneur       2   married           1  secondary             1   
3   47   blue-collar       1   married           1       None             3   
4   33          None      11    single           2       None             3   
5   35    management       4   married           1   tertiary             2   
6   28    management       4    single           2   tertiary             2   
7   42  entrepreneur       2  divorced           0   tertiary             2   
8   58       retired       5   married           1    primary             0   
9   43    technician       9    single           2  secondary             1   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5   may       261        1   
1      no           0       29  ...          2    5   may       151        1   
2      no           0        2  ...          2    5   may        76        1   
3      no           0     1506  ...          2    5   may        92        1   
4      no           0        1  ...          2    5   may       198        1   
5      no           0      231  ...          2    5   may       139        1   
6      no           0      447  ...          2    5   may       217        1   
7     yes           1        2  ...          2    5   may       380        1   
8      no           0      121  ...          2    5   may        50        1   
9      no           0      593  ...          2    5   may        55        1   

   pdays  previous poutcome  numpoutcome  deposit  
0     -1         0     None            3       no  
1     -1         0     None            3       no  
2     -1         0     None            3       no  
3     -1         0     None            3       no  
4     -1         0     None            3       no  
5     -1         0     None            3       no  
6     -1         0     None            3       no  
7     -1         0     None            3       no  
8     -1         0     None            3       no  
9     -1         0     None            3       no  

[10 rows x 25 columns]

Y para el mes.

In [ ]:
analisis.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

Se crea una función para reemplazar los nombres del mes por el número que corresponde.

In [ ]:
def mes(month):
  if month == "jan":
    return int("1")
  elif month == "feb":
    return int("2")
  elif month == "mar":
    return int("3")
  elif month == "apr":
    return int("4")
  elif month == "may":
    return int("5")
  elif month == "jun":
    return int("6")
  elif month == "jul":
    return int("7")
  elif month == "aug":
    return int("8")
  elif month == "sep":
    return int("9")
  elif month == "oct":
    return int("10")
  elif month == "nov":
    return int("11")
  else:
    return int("12")

In [ ]:
analisis.month = analisis.month.apply(mes)

In [ ]:
analisis.month.unique()

array([ 5,  6,  7,  8, 10, 11, 12,  1,  2,  3,  4,  9])

In [ ]:
analisis.head()

age           job  numjob  marital  nummarital  education  numeducation  \
0   58    management       4  married           1   tertiary             2   
1   44    technician       9   single           2  secondary             1   
2   33  entrepreneur       2  married           1  secondary             1   
3   47   blue-collar       1  married           1       None             3   
4   33          None      11   single           2       None             3   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   
4      no           0        1  ...          2    5     5       198        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None            3       no  
1     -1         0      None            3       no  
2     -1         0      None            3       no  
3     -1         0      None            3       no  
4     -1         0      None            3       no  

[5 rows x 25 columns]

 ## **<font color="#07a8ed">Imputación de valores faltantes</font>**

In [ ]:
analisis.head(10)

age           job  numjob   marital  nummarital  education  numeducation  \
0   58    management       4   married           1   tertiary             2   
1   44    technician       9    single           2  secondary             1   
2   33  entrepreneur       2   married           1  secondary             1   
3   47   blue-collar       1   married           1       None             3   
4   33          None      11    single           2       None             3   
5   35    management       4   married           1   tertiary             2   
6   28    management       4    single           2   tertiary             2   
7   42  entrepreneur       2  divorced           0   tertiary             2   
8   58       retired       5   married           1    primary             0   
9   43    technician       9    single           2  secondary             1   

  default  numdefault  balance  ... numcontact  day month  duration campaign  \
0      no           0     2143  ...          2    5     5       261        1   
1      no           0       29  ...          2    5     5       151        1   
2      no           0        2  ...          2    5     5        76        1   
3      no           0     1506  ...          2    5     5        92        1   
4      no           0        1  ...          2    5     5       198        1   
5      no           0      231  ...          2    5     5       139        1   
6      no           0      447  ...          2    5     5       217        1   
7     yes           1        2  ...          2    5     5       380        1   
8      no           0      121  ...          2    5     5        50        1   
9      no           0      593  ...          2    5     5        55        1   

   pdays  previous  poutcome  numpoutcome  deposit  
0     -1         0      None            3       no  
1     -1         0      None            3       no  
2     -1         0      None            3       no  
3     -1         0      None            3       no  
4     -1         0      None            3       no  
5     -1         0      None            3       no  
6     -1         0      None            3       no  
7     -1         0      None            3       no  
8     -1         0      None            3       no  
9     -1         0      None            3       no  

[10 rows x 25 columns]

 ### **<font color="#07a8ed">Media</font>**

In [ ]:
print(analisis.education[3])

None


In [ ]:
analisis.numeducation[3]

3

In [ ]:
imputacion = SimpleImputer(missing_values=3, strategy="mean")

In [ ]:
analisis.numeducation = imputacion.fit_transform(analisis[["numeducation"]])

In [ ]:
analisis.numeducation = round(analisis.numeducation,3)

In [ ]:
analisis.numeducation[3]

1.149

 ### **<font color="#07a8ed">Mediana</font>**

In [ ]:
print(analisis.poutcome[0])

None


In [ ]:
analisis.numpoutcome[0]

3

In [ ]:
imputacion = SimpleImputer(missing_values=3, strategy="median")

In [ ]:
analisis.numpoutcome = imputacion.fit_transform(analisis[["numpoutcome"]])

In [ ]:
analisis.numpoutcome[4]

1.0

 ### **<font color="#07a8ed">Moda (el más frecuente)</font>**

In [ ]:
print(analisis.contact[0])

None


In [ ]:
analisis.numcontact[0]

2

In [ ]:
imputacion = SimpleImputer(missing_values=2, strategy="most_frequent")

In [ ]:
analisis.numcontact = imputacion.fit_transform(analisis[["numcontact"]])

In [ ]:
analisis.numcontact[0]

0