 # **<font color="DarkBlue">Generación de muestras aleatorias</font>**

<p align="center">
<img src="https://numpy.org/images/logo.svg" width="80" height="">
</p>


https://numpy.org

<p align="justify">
✅ La generación de números aleatorios es fundamental en estadística y simulación de experimentos. <code>NumPy</code> proporciona una amplia gama de funciones en el módulo <code>numpy.random</code> para generar muestras aleatorias de diferentes distribuciones.
<br><br>
👀 A continuación, se presentan algunas distribuciones comunes y ejemplos de su aplicación:

<p align="justify"> 👀 Por convención, de esta manera se importa <code>Numpy</code> y se importa <code>plotly</code> que vamos a utilizar para visualizar:  </p>

In [1]:
import numpy as np

In [2]:
import plotly.express as px

 ## **<font color="DarkBlue">Distribución uniforme</font>**

<p align="justify">
✅ La distribución uniforme genera números aleatorios en un rango especificado con igual probabilidad. Esto puede ser útil para simular eventos donde todas las posibilidades son igualmente probables.
<br><br>
La distribución uniforme es un tipo de distribución de probabilidad en la que todos los valores dentro de un rango específico son igualmente probables. Para una variable aleatoria \( X \) con una distribución uniforme continua en el intervalo \([a, b]\), la función de densidad de probabilidad (pdf) se define como:
<br><br>
$$ f(x) =
\begin{cases}
\frac{1}{b - a} & \text{si } a \leq x \leq b \\
0 & \text{en otro caso}
\end{cases}
$$
<br><br>
donde \( a \) y \( b \) son los límites inferior y superior del intervalo, respectivamente. La distribución uniforme puede ser discreta o continua, dependiendo de si los valores posibles de la variable aleatoria son finitos o infinitos.
<br><br>
<mark>La distribución uniforme puede ser utilizada para modelar situaciones en las que todos los resultados posibles son igualmente probables.</mark> Un ejemplo común es la simulación de precios de mercado en ausencia de información sobre la demanda y la oferta, donde se asume que cualquier precio dentro de un rango específico es igualmente probable. Esto puede ayudar en la evaluación de riesgos y en la toma de decisiones bajo incertidumbre.


### La probabilidad simple es el cálculo de la posibilidad de que un evento específico ocurra cuando se realiza un experimento que tiene un solo resultado posible por cada intento. Es uno de los conceptos fundamentales que utilizas en tus análisis de datos y modelos de machine learning para evaluar la frecuencia de un suceso dentro de un conjunto total de posibilidades.Fórmula FundamentalPara calcularla, se utiliza la regla de Laplace, la cual se expresa matemáticamente como:$$P(A) = \frac{\text{Número de casos favorables}}{\text{Número total de casos posibles}}$$


<p align="justify">
👀 Por ejemplo, supongamos que queremos modelar la distribución de tiempos de espera de los clientes en una tienda, donde los clientes pueden llegar en cualquier momento dentro de un intervalo de tiempo específico.

In [3]:
np.random.seed(0) ## establecer semilla

In [4]:
# Generar datos de tiempos de espera de los clientes (distribución uniforme)dentro del rango tienen la misma probabilidad de ser elegidos.

tiempos_espera = np.random.uniform(low=0, high=30, size=1000)  # Tiempos de espera en minutos, de 0 a 30 minutos y tamaño de la muestra

In [5]:
tiempos_espera.round(2)

array([1.646e+01, 2.146e+01, 1.808e+01, 1.635e+01, 1.271e+01, 1.938e+01,
       1.313e+01, 2.675e+01, 2.891e+01, 1.150e+01, 2.375e+01, 1.587e+01,
       1.704e+01, 2.777e+01, 2.130e+00, 2.610e+00, 6.100e-01, 2.498e+01,
       2.334e+01, 2.610e+01, 2.936e+01, 2.397e+01, 1.384e+01, 2.342e+01,
       3.550e+00, 1.920e+01, 4.300e+00, 2.834e+01, 1.566e+01, 1.244e+01,
       7.940e+00, 2.323e+01, 1.368e+01, 1.705e+01, 5.600e-01, 1.853e+01,
       1.836e+01, 1.851e+01, 2.831e+01, 2.045e+01, 1.079e+01, 1.311e+01,
       2.093e+01, 1.810e+00, 2.000e+01, 2.012e+01, 6.310e+00, 3.870e+00,
       9.460e+00, 1.091e+01, 1.711e+01, 1.316e+01, 2.965e+01, 3.060e+00,
       6.270e+00, 4.840e+00, 1.959e+01, 7.600e+00, 1.399e+01, 7.330e+00,
       4.770e+00, 3.310e+00, 1.969e+01, 4.150e+00, 5.900e+00, 1.106e+01,
       2.463e+01, 2.910e+00, 2.514e+01, 2.880e+00, 2.929e+01, 1.406e+01,
       2.930e+01, 1.815e+01, 2.218e+01, 1.180e+00, 8.480e+00, 3.610e+00,
       8.880e+00, 3.560e+00, 9.540e+00, 1.243e+01, 

In [6]:
px.histogram(x = tiempos_espera,
             title="Distribución Uniforme de tiempos de espera de clientes",
             labels={"x":"Tiempo de Espera (minutos)"},
             template="gridon").update_layout(bargap=0.2)

In [7]:
# Convertimos a formato MM:SS  ## conversion de datos en datos de tiempo
tiempos_reloj = [f"{int(t):02d}:{int((t % 1) * 60):02d}" for t in tiempos_espera] # conversion en tiempo reloj

In [8]:
tiempos_reloj

['16:27',
 '21:27',
 '18:04',
 '16:20',
 '12:42',
 '19:22',
 '13:07',
 '26:45',
 '28:54',
 '11:30',
 '23:45',
 '15:52',
 '17:02',
 '27:46',
 '02:07',
 '02:36',
 '00:36',
 '24:58',
 '23:20',
 '26:06',
 '29:21',
 '23:58',
 '13:50',
 '23:24',
 '03:32',
 '19:11',
 '04:18',
 '28:20',
 '15:39',
 '12:26',
 '07:56',
 '23:13',
 '13:41',
 '17:03',
 '00:33',
 '18:31',
 '18:21',
 '18:30',
 '28:18',
 '20:27',
 '10:47',
 '13:06',
 '20:55',
 '01:48',
 '20:00',
 '20:07',
 '06:18',
 '03:52',
 '09:27',
 '10:54',
 '17:06',
 '13:09',
 '29:39',
 '03:03',
 '06:15',
 '04:50',
 '19:35',
 '07:35',
 '13:59',
 '07:19',
 '04:46',
 '03:18',
 '19:41',
 '04:08',
 '05:53',
 '11:03',
 '24:37',
 '02:54',
 '25:08',
 '02:52',
 '29:17',
 '14:03',
 '29:18',
 '18:08',
 '22:10',
 '01:10',
 '08:29',
 '03:36',
 '08:53',
 '03:33',
 '09:32',
 '12:25',
 '01:55',
 '20:46',
 '16:59',
 '07:57',
 '15:41',
 '02:49',
 '17:16',
 '27:52',
 '09:33',
 '20:01',
 '03:57',
 '21:29',
 '08:40',
 '05:29',
 '17:35',
 '00:36',
 '24:52',
 '00:08',


 ## **<font color="DarkBlue">Distribución normal</font>**

✅ La distribución normal es una de las distribuciones más importantes en estadística y modelado de datos. Puede representar muchos fenómenos en la naturaleza y los negocios, como la altura de las personas o los ingresos de una población.
<br><br>
La distribución normal, también conocida como distribución de Gauss, es una distribución de probabilidad continua que se caracteriza por su forma de campana simétrica. Para una variable aleatoria $X $ con una distribución normal, la función de densidad de probabilidad se define como:
<br><br>
$$ f(x) = \frac{1}{\sqrt{2 \pi \sigma^2}} \exp\left(-\frac{(x - \mu)^2}{2 \sigma^2}\right) $$
<br>
donde:
- $ \mu $ es la media de la distribución,
- $ \sigma $ es la desviación estándar,
- $ \sigma^2 $ es la varianza,
- $ \exp $ es la función exponencial.

<p align="justify">
<br>
La distribución normal es fundamental en la estadística y la probabilidad debido a su relación con el teorema central del límite, que establece que, bajo ciertas condiciones, la suma de muchas variables aleatorias independientes y identicamente distribuidas tiende a una distribución normal, independientemente de la distribución original de las variables.
<br><br>
La distribución normal es ampliamente utilizada en diversas áreas para modelar fenómenos naturales y procesos industriales. Un ejemplo común es la modelación de los retornos de inversión en mercados financieros, donde se asume que los retornos siguen una distribución normal. Esto permite realizar análisis de riesgo y optimización de carteras, basados en la probabilidad de diferentes niveles de retorno y la volatilidad asociada.
<br><br>
👀 Por ejemplo, supongamos que queremos simular los ingresos anuales de una muestra de empleados de una empresa:


In [9]:
# Simular ingresos anuales de una muestra de empleados
np.random.seed(0)
ingresos_anuales = np.random.normal(loc=90000, scale=10000, size=400).round(2)  ## media, desviacion estandard, tamaño

In [10]:
ingresos_anuales

array([107640.52,  94001.57,  99787.38, 112408.93, 108675.58,  80227.22,
        99500.88,  88486.43,  88967.81,  94105.99,  91440.44, 104542.74,
        97610.38,  91216.75,  94438.63,  93336.74, 104940.79,  87948.42,
        93130.68,  81459.04,  64470.1 ,  96536.19,  98644.36,  82578.35,
       112697.55,  75456.34,  90457.59,  88128.16, 105327.79, 104693.59,
        91549.47,  93781.63,  81122.14,  70192.04,  86520.88,  91563.49,
       102302.91, 102023.8 ,  86126.73,  86976.97,  79514.47,  75799.82,
        72937.3 , 109507.75,  84903.48,  85619.26,  77472.05,  97774.9 ,
        73861.02,  87872.6 ,  81045.33,  93869.02,  84891.95,  78193.68,
        89718.18,  94283.32,  90665.17,  93024.72,  83656.78,  86372.59,
        83275.4 ,  86404.47,  81868.54,  72737.17,  91774.26,  85982.19,
        73698.02,  94627.82,  80927.02,  90519.45,  97290.91,  91289.83,
       101394.01,  77651.74,  94023.42,  83151.9 ,  81292.03,  84211.5 ,
        86884.47,  90561.65,  78348.5 ,  99008.26, 

In [11]:
px.histogram(x = ingresos_anuales,
             title="Distribución ingresos anuales de empleados",
             labels={"x":"Ingresos anuales"},
             template="gridon").update_layout(bargap=0.2) ## gridon colores//espacio entre barras para que no salgan pegadas

In [12]:
import numpy as np
import plotly.figure_factory as ff

# Suponiendo que 'ingresos_anuales' es tu array de datos
# Ejemplo: ingresos_anuales = np.random.normal(50000, 15000, 1000)

# Creamos el distplot (Histograma + Curva KDE)
fig = ff.create_distplot(
    [ingresos_anuales],
    group_labels=['Ingresos'],
    show_hist=True, ### barras de distribucion del histograma
    show_rug=False,  ## desactiva grafico "rug" alfombra
    bin_size=2000 # Ajusta según la dispersión de tus datos
)

# Aplicamos tus estilos y etiquetas
fig.update_layout(
    title="Distribución ingresos anuales de empleados",
    xaxis_title="Ingresos anuales",
    yaxis_title="Densidad / Frecuencia",
    template="gridon",
    bargap=0.2
)

fig.show()

<p align="justify">
👀 Otro ejemplo, supongamos que queremos modelar la distribución de la altura de los clientes de una tienda de camisas para determinar el tamaño promedio que deberíamos tener en stock....

In [13]:
# Generar datos de altura de los clientes (distribución normal)
altura_clientes = np.random.normal(loc=170, scale=10, size=1000)  ###media, desviacion estandard,tamaño

In [14]:
altura_clientes.round(2)

array([164.01, 158.84, 177.67, 173.56, 152.31, 173.55, 178.15, 170.59,
       168.15, 161.92, 155.53, 178.  , 166.91, 167.67, 187.33, 176.85,
       173.71, 171.42, 185.2 , 187.2 , 179.3 , 175.82, 149.05, 171.24,
       168.7 , 170.94, 179.43, 142.6 , 164.31, 172.7 , 165.33, 155.83,
       178.69, 172.77, 160.29, 173.15, 178.22, 170.05, 178.01, 170.78,
       166.05, 158.41, 169.14, 171.94, 178.76, 168.85, 174.57, 160.35,
       162.17, 168.9 , 159.45, 178.2 , 174.63, 172.79, 173.39, 190.21,
       165.31, 147.99, 171.99, 169.49, 164.82, 160.21, 165.61, 171.81,
       164.97, 194.12, 160.39, 162.07, 147.11, 172.51, 149.84, 164.61,
       167.24, 162.9 , 187.39, 179.94, 183.19, 161.18, 181.29, 174.96,
       177.71, 180.29, 160.91, 165.76, 178.63, 143.44, 185.13, 175.53,
       169.54, 172.21, 159.7 , 166.5 , 181.  , 182.98, 196.96, 169.26,
       163.41, 164.86, 159.82, 169.22, 173.83, 169.66, 180.96, 167.66,
       166.53, 164.19, 153.67, 154.32, 158.21, 183.01, 178.95, 183.75,
      

In [15]:
px.histogram(x=altura_clientes,  ## define variable del grafico
             nbins=30, ## Especifica el número de contenedores (barras)
             title="Distribución de altura de los clientes", ## titulo grafico
             labels={"x":"Altura (cm)"}, ## Renombra la etiqueta del eje X para que sea más legible y profesional, incluyendo las unidades de medida en lugar de mostrar el nombre de la variable técnica.
             template="gridon").update_layout(bargap=0.2)  ## color y añade una función de diseño que añade un espacio del 20% entre las barras del histograma

In [16]:
import plotly.figure_factory as ff

# Suponiendo que ya tienes definido 'altura_clientes'
# fig = ff.create_distplot([data], group_labels, ...)

fig = ff.create_distplot(
    [altura_clientes],
    group_labels=['Clientes'],
    bin_size=2,        # Ajustado para que sea similar a nbins=30
    show_hist=True, ## Indica que quieres que las barras del histograma sean visibles detrás de la línea de tendencia.
    show_rug=False     # Quita las marcas inferiores para un look más limpio
)

fig.update_layout(
    title="Distribución de altura de los clientes",
    xaxis_title="Altura (cm)",  ## Establece la etiqueta del eje X (horizontal). Es una buena práctica incluir siempre las unidades de medida (en este caso, cm) para dar contexto a los números.
    yaxis_title="Densidad", ## Establece la etiqueta del eje Y (vertical).
    template="gridon",  ## Define el "tema" visual del gráfico
    bargap=0.2  ## Controla el espacio de separación entre las barras del histograma.
)

fig.show()

 ## **<font color="DarkBlue">Distribución binomial</font>**

<p align="justify">
✅ La distribución binomial modela el número de éxitos en una serie de ensayos independientes con una probabilidad de éxito constante.
<br><br>
La distribución binomial es una distribución de probabilidad discreta que describe el número de éxitos en una secuencia de $ n $ experimentos de Bernoulli independientes, cada uno con una probabilidad de éxito $ p $. La función de masa de probabilidad  para una variable aleatoria $ X $ con una distribución binomial se define como:
<br><br>
\[ P(X = k) = \binom{n}{k} p^k (1 - p)^{n - k} \]
<br><br>
donde:

- $ \binom{n}{k} $ es el coeficiente binomial, que se calcula como $ \frac{n!}{k!(n - k)!} $,
- $ n $ es el número de experimentos,
- $ k $ es el número de éxitos,
- $ p $ es la probabilidad de éxito en cada experimento,
- $ 1 - p $ es la probabilidad de fracaso.

<p align="justify">
<br>
La distribución binomial es útil para modelar situaciones en las que hay dos posibles resultados (éxito o fracaso) en una serie de experimentos repetidos de manera independiente.
<br><br>
Un ejemplo común es la evaluación del número de ventas exitosas en una serie de llamadas de telemarketing, donde cada llamada puede resultar en una venta (éxito) o no (fracaso), y la probabilidad de éxito es constante para cada llamada. Esto puede ayudar en la planificación de estrategias de ventas y en la estimación de ingresos futuros basados en la probabilidad de éxito y el número de intentos.
<br><br>
👀 Por ejemplo, supongamos que queremos simular el número de clientes que compran un producto en una tienda en línea durante una hora:


In [17]:
# Simular el número de clientes que compran un producto en una tienda en línea durante una hora
np.random.seed(0)
num_clientes = np.random.binomial(n=100, p=0.1, size=1)  ## numero de ensayos, probabilidad de exito, tamaño
num_clientes

array([10])

In [18]:
num_clientes  ## 10 exitos de 100 intentos

array([10])

### 10 exitos de 100 intentos

<p align="justify">
👀 Otro ejemplo, supongamos que queremos modelar la probabilidad de que un cliente realice una compra en una tienda en línea, donde la probabilidad de compra es del 30% y realizamos 100 intentos de compra...

In [19]:
# Simular el número de clientes que compran un producto en una tienda en línea
num_clientes_compran = np.random.binomial(n=100, p=0.3, size=800)
##(Ensayos): Imagina que cada día entran 100 clientes a una tienda. Este es el número total de "oportunidades" en cada experimento.
##Es la probabilidad de éxito de cada cliente. Aquí nos dice que hay un 30% de probabilidad de que un cliente compre.
# ##Es cuántas veces repetimos la simulación. En este caso, estamos simulando, lo que pasaría durante 800 días diferentes. %%

In [20]:
num_clientes_compran

array([33, 31, 30, 29, 32, 29, 36, 38, 29, 34, 30, 31, 37, 23, 24, 21, 34,
       33, 35, 39, 34, 29, 34, 25, 32, 25, 37, 30, 29, 27, 33, 29, 31, 21,
       31, 31, 31, 37, 32, 28, 29, 32, 23, 32, 32, 26, 25, 28, 28, 31, 29,
       41, 24, 26, 25, 32, 27, 30, 27, 25, 24, 32, 25, 26, 28, 34, 24, 35,
       24, 39, 30, 39, 31, 33, 22, 27, 25, 27, 25, 28, 29, 23, 32, 31, 27,
       30, 24, 31, 37, 28, 32, 25, 33, 27, 26, 31, 21, 34, 19, 32, 27, 33,
       38, 27, 31, 31, 31, 26, 38, 29, 35, 32, 28, 34, 29, 35, 31, 35, 32,
       33, 30, 38, 32, 29, 31, 21, 28, 32, 27, 31, 29, 25, 28, 31, 31, 31,
       32, 32, 29, 36, 28, 29, 36, 34, 32, 24, 36, 33, 44, 25, 35, 25, 31,
       25, 35, 34, 31, 29, 23, 32, 29, 33, 35, 39, 35, 20, 28, 33, 26, 30,
       23, 26, 21, 34, 26, 28, 37, 32, 22, 26, 31, 31, 27, 37, 31, 30, 31,
       33, 28, 29, 26, 26, 37, 33, 30, 27, 27, 23, 29, 28, 32, 29, 26, 21,
       23, 32, 29, 30, 36, 41, 26, 32, 27, 21, 33, 28, 29, 31, 34, 31, 35,
       27, 34, 26, 38, 32

In [21]:
px.histogram(x = num_clientes_compran,  ## Le pasas el array de los 800 resultados que generaste con la distribución binomial
             nbins = 20, ## Le pides a Plotly que agrupe los datos en 20 columnas (contenedores)
             title="Número de clientes que compran un producto",  ## El nombre que aparecerá en la parte superior del gráfico.
             labels={"x":"Número de Clientes que Compran"},##Sirve para renombrar el eje X.
             template="gridon").update_layout(bargap=0.2) ## el estilo visual con cuadrícula clara para facilitar la lectura de los datos.

In [22]:
import numpy as np
import plotly.figure_factory as ff

# Calculamos el ancho de bin para mantener tus 20 divisiones
rango = np.max(num_clientes_compran) - np.min(num_clientes_compran)
ancho_bin = rango / 20 if rango > 0 else 1

# Creamos el gráfico con la curva KDE
fig = ff.create_distplot(
    [num_clientes_compran],##Le pasas la lista de los 800 resultados de ventas que generaste con NumPy.
    group_labels=['Compras'],##Asigna el nombre "Compras" a la leyenda del gráfico.
    bin_size=ancho_bin,##Aquí estás usando una variable (seguramente definida antes en tu código) para controlar el grosor de las barras.
    show_hist=True,##Muestra las barras del histograma,
    show_rug=False  ##Mantiene el estilo limpio.
)

# Aplicamos tu configuración de diseño
fig.update_layout(
    title="Número de clientes que compran un producto",  ## Establece el encabezado principal.
    xaxis_title="Número de Clientes que Compran",  ##Nombra el eje horizontal
    yaxis_title="Densidad", ###Nombra el eje vertical.
    template="gridon", ## Aplica un tema visual predefinido
    bargap=0.2 ##añade un espacio del 20% entre las barras del histograma.
)##En un distplot, el eje Y no muestra el conteo de días, sino la Probabilidad Relativa.
###Esto es necesario para que la curva de densidad (la línea curva) pueda dibujarse en la misma escala que las barras.

fig.show()

 ## **<font color="DarkBlue">Distribución de Poisson</font>**

<p align="justify">
✅ La distribución de Poisson modela el número de eventos que ocurren en un intervalo de tiempo o espacio fijo, dado que los eventos ocurren a una tasa constante e independientemente del tiempo o espacio.
<br><br>
La distribución de Poisson es una distribución de probabilidad discreta que describe el número de eventos que ocurren en un intervalo de tiempo o espacio fijo, cuando estos eventos ocurren con una tasa promedio constante y de manera independiente unos de otros. La función de masa de probabilidad para una variable aleatoria $ X $ con una distribución de Poisson se define como:
<br><br>
\[ P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!} \]

donde:
- $ \lambda $ es la tasa promedio de ocurrencia de eventos,
- $ k $ es el número de eventos,
- $ e $ es la base del logaritmo natural (aproximadamente 2.71828),
- $ k! $ es el factorial de $ k $.

<p align="justify">
<br>
La distribución de Poisson es útil para modelar situaciones en las que se cuenta el número de eventos que ocurren en un intervalo determinado.
<br><br>
Un ejemplo común es la modelación del número de llegadas de clientes a un banco en una hora determinada, donde se asume que las llegadas son independientes y ocurren con una tasa promedio constante. Esto puede ayudar en la planificación de recursos, como la dotación de personal, para asegurar un servicio eficiente basado en la tasa esperada de llegadas.
<br><br>
👀 Por ejemplo, supongamos que queremos simular el número de llamadas de servicio al cliente recibidas en una hora`


In [23]:
# Simular el número de llamadas de servicio al cliente recibidas en una hora
np.random.seed(0)
num_llamadas = np.random.poisson(lam=10, size=1)  ## número promedio de eventos, tamaño
num_llamadas

array([10])

- **lam $=10$**: Este es el parámetro λ de la distribución de Poisson, que representa la tasa promedio de ocurrencia de eventos. En este caso, se asume que, en promedio, se reciben 10 llamadas de servicio al cliente por hora.
- **size $=1$**: Esto especifica el número de muestras a generar. En este caso, se genera una sola muestra.

<p align="justify">
👀 Otro ejemplo, supongamos que queremos modelar el número de llamadas de servicio al cliente recibidas en una hora, donde recibimos un promedio de 10 llamadas por hora, pero generamos 1000 muestras.


In [24]:
# Simular el número de llamadas de servicio al cliente recibidas en una hora
np.random.seed(0)
num_llamadas = np.random.poisson(lam=10, size=1000)  ## tasa media de ocurrencia, y 1000 observaciones

In [25]:
num_llamadas

array([10, 11,  9,  9, 18, 13,  4, 10, 10,  8, 10, 11, 16,  9, 12, 12,  7,
        8, 11,  7, 11, 10,  6, 11,  7, 13, 14, 12,  8,  8,  8, 11, 10,  8,
        6,  8, 11, 13, 12,  7, 11,  9, 12, 13, 14, 14, 12, 17,  9, 12, 11,
        6, 11, 11, 11, 15,  9, 13,  6,  6, 13,  9, 12, 12, 10,  7, 13, 12,
        6, 11, 16, 10, 12,  9, 12,  7,  4,  8,  9, 12, 10, 12,  8, 11,  8,
       12,  7, 10,  7,  9,  8, 14, 10, 12, 11,  6,  9, 15, 10, 18,  7,  8,
        4, 16,  8, 11,  8, 10,  9, 13, 10,  8,  9,  6, 12, 13,  4, 12,  9,
        8,  3,  8, 12,  8,  7,  7, 11,  9, 10, 13, 10, 11,  9, 10,  8,  7,
       10, 14, 12, 15, 12, 13,  7, 10, 14, 17, 13, 11,  4,  9,  9, 14,  8,
       11,  4,  7,  6,  9, 11, 13,  7,  7, 10, 10, 12,  9, 16,  7,  7, 17,
       12,  8,  9,  7,  9, 14, 11, 16,  4,  6,  6,  9,  8, 15, 10, 10,  7,
        8, 10, 14,  7,  5, 12, 11,  7, 10,  5, 11,  7, 11, 11, 18, 10, 13,
        9, 12,  7, 11, 15,  6, 17,  9,  6,  9, 12,  2, 12,  9,  6, 12, 11,
        8, 10, 10, 19,  5

In [26]:
px.histogram(x = num_llamadas,
             nbins=20,
             title="Distribución de Poisson de llamadas de Servicio al Cliente",
             labels={"x":"Número de llamadas"},
             template="gridon").update_layout(bargap=0.2)

 # **<font color="DarkBlue">Cálculo de medidas de tendencia central y dispersión</font>**

<p align="justify">
✅ Las medidas de tendencia central y dispersión son fundamentales en estadística para resumir y comprender la distribución de los datos. NumPy proporciona funciones para calcular estas medidas de manera eficiente. Son herramientas estadísticas fundamentales que se utilizan para describir y resumir conjuntos de datos.
<br><br>
A continuación, se presenta cómo calcular y utilizar estas medidas en contextos empresariales:
</p>

 ## **<font color="DarkBlue">Medidas de tendencia central</font>**

 ### **<font color="DarkBlue">Media (Promedio)</font>**

<p align="justify">
✅ La media es la suma de todos los valores dividida por el número de valores. Es útil para calcular el valor promedio de un conjunto de datos.
<br><br>
  $$
  \text{Media} = \frac{\sum_{i=1}^{n} x_i}{n}
  $$

<br>

donde:
- $ x_i $ son los valores del conjunto y
- $ n $ es el número total de valores.

<p align="justify">
<br>
👀 Por ejemplo, para calcular el promedio de las ventas mensuales de una empresa...


In [27]:
# Ventas mensuales de una empresa en miles de dólares

ventas_mensuales = np.array([100, 120, 110, 130, 140])
ventas_mensuales

array([100, 120, 110, 130, 140])

In [28]:
# Calcular la media de las ventas mensuales

media_ventas = np.mean(ventas_mensuales)
media_ventas

np.float64(120.0)

In [29]:
media_ventas

np.float64(120.0)

In [30]:
import plotly.graph_objects as go
import numpy as np

# Calculamos la media (como ya hiciste)
media_ventas = np.mean(ventas_mensuales)

# Etiquetas para los meses (ajustar según la cantidad de datos en tu array)
meses = [f"Mes {i+1}" for i in range(len(ventas_mensuales))]  ## es un bucle en meses generamos y contamos rango

fig = go.Figure()

# 1. Trazamos las ventas mensuales
fig.add_trace(go.Scatter( ## agrega trazo y grafico de dispersion
    x=meses,
    y=ventas_mensuales,
    mode='lines+markers',  ## la línea que conecta los puntos como los puntos (marcadores) individuales
    name='Ventas Mensuales',  ## Es el nombre que aparecerá en la leyenda interactiva del gráfico.
    line=dict(color='#1f77b4', width=3)  ## Define la estética de la línea. El color #1f77b4 es un azul estándar muy profesional y el width=3 le da un grosor suficiente
))

# 2. Agregamos la línea de la media
fig.add_trace(go.Scatter( ##Esta función se usa para "dibujar" una nueva capa sobre el gráfico original
    x=meses,  ## variable x
    y=[media_ventas] * len(ventas_mensuales),##Para dibujar una línea horizontal, necesitas que el valor de Y sea el mismo en todos los puntos.
    mode='lines',  ##Le indica a Plotly que conecte los puntos con una línea y que no muestre los puntos individuales (marcadores).
    name=f'Media: {media_ventas:.2f}',  ##Es el nombre que aparecerá en la leyenda.
    line=dict(color='red', width=2, dash='dash') # Línea punteada roja,Define el grosor.Cambia la línea sólida por una línea punteada.
))

# Configuración de diseño
fig.update_layout(
    title="Análisis de Ventas Mensuales respecto a la Media",
    xaxis_title="Periodo",
    yaxis_title="Ventas",
    template="gridon",
    hovermode="x unified"  ## Al pasar el ratón por el gráfico, aparece una única etiqueta flotante que muestra los valores de todas las líneas al mismo tiempo para esa coordenada X.
)

fig.show()

 ### **<font color="DarkBlue">Mediana</font>**

<p align="justify">
✅ La mediana es el valor que se encuentra en el centro de un conjunto de datos ordenados. Es útil cuando los datos están sesgados o tienen valores atípicos. Es el valor que se encuentra en el medio de un conjunto de datos ordenados.
<br><br>
Si el número de observaciones es impar, la mediana es el valor central. Si es par, la mediana se calcula como el promedio de los dos valores centrales.
<br><br>
  $$
  \text{Mediana} =
  \begin{cases}
  x_{\frac{n+1}{2}} & \text{si } n \text{ es impar} \\
  \frac{x_{\frac{n}{2}} + x_{\frac{n}{2} + 1}}{2} & \text{si } n \text{ es par}
  \end{cases}
  $$
<br><br>
👀 Por ejemplo, para calcular la mediana de los ingresos anuales de una muestra de empleados...


In [31]:
# Ingresos anuales de una muestra de empleados en miles de dólares

ingresos_anuales = np.array([40000, 50000, 60000, 70000, 80000, 90000, 100000])
ingresos_anuales

array([ 40000,  50000,  60000,  70000,  80000,  90000, 100000])

In [32]:
# Calcular la mediana de los ingresos anuales

mediana_ingresos = np.median(ingresos_anuales)
mediana_ingresos

np.float64(70000.0)

In [33]:
import plotly.figure_factory as ff
import numpy as np

# Calculamos la mediana
mediana_ingresos = np.median(ingresos_anuales)

# Creamos el histograma con curva
fig = ff.create_distplot(
    [ingresos_anuales],
    group_labels=['Ingresos'],
    show_hist=True,
    show_rug=False,
    bin_size=2000
)

# Agregamos una línea vertical para la mediana
fig.add_vline(
    x=mediana_ingresos,
    line_dash="dash",
    line_color="green",
    annotation_text=f"Mediana: {mediana_ingresos:,.2f}",
    annotation_position="top right"
)

fig.update_layout(
    title="Distribución de Ingresos con Mediana",
    xaxis_title="Ingresos anuales",
    yaxis_title="Densidad",
    template="gridon",
    bargap=0.2
)

fig.show()

 ### **<font color="DarkBlue">Moda</font>**

<p align="justify">
✅ La moda es el valor que aparece con mayor frecuencia en un conjunto de datos. Es útil para identificar patrones de comportamiento.
<br><br>
👀 Por ejemplo, para calcular la moda de los productos más vendidos en una tienda:


In [34]:
# Número de ventas diarias de diferentes productos en una tienda

ventas_diarias = np.array([20, 30, 25, 25, 40, 30, 30, 25, 40, 25, 30, 30, 45, 45, 30])
ventas_diarias

array([20, 30, 25, 25, 40, 30, 30, 25, 40, 25, 30, 30, 45, 45, 30])

In [35]:
# Calcular la moda de las ventas diarias

moda_ventas = np.argmax(np.bincount(ventas_diarias))
moda_ventas

np.int64(30)

In [36]:
import numpy as np
import plotly.figure_factory as ff
from scipy import stats

# 1. Calculamos la moda
# stats.mode devuelve un objeto; extraemos el valor
moda_resultado = stats.mode(num_llamadas, keepdims=True)
moda_valor = moda_resultado.mode[0]

# 2. Creamos el gráfico de distribución
fig = ff.create_distplot(
    [num_llamadas],
    group_labels=['Datos'],
    show_hist=True,
    show_rug=False,
    bin_size=1
)

# 3. Agregamos una línea vertical en la moda
fig.add_vline(
    x=moda_valor,
    line_width=3,
    line_color="orange",
    annotation_text=f"Moda: {moda_valor}",
    annotation_position="top left"
)

fig.update_layout(
    title="Frecuencia de Datos y su Valor Modal",
    xaxis_title="Valores",
    yaxis_title="Densidad",
    template="gridon",
    bargap=0.2
)

fig.show()

 ## **<font color="DarkBlue">Medidas de dispersión</font>**

 ### **<font color="DarkBlue">Varianza</font>**

<p align="justify">
✅ La varianza mide la dispersión de los datos con respecto a la media. Es útil para comprender la dispersión de los datos. Mide la variabilidad de los datos respecto a la media. Se calcula como el promedio de las diferencias al cuadrado entre cada valor y la media.
<br><br>
  $$
  \text{Varianza} = \frac{\sum_{i=1}^{n} (x_i - \text{Media})^2}{n}
  $$
<br>
👀 Por ejemplo, para calcular la varianza de los tiempos de entrega de los pedidos de una empresa:


In [37]:
# Tiempos de entrega de los pedidos en días

tiempos_entrega = np.array([2, 3, 2, 4, 3, 5, 2, 5, 3, 6, 3, 2, 5, 4])
tiempos_entrega

array([2, 3, 2, 4, 3, 5, 2, 5, 3, 6, 3, 2, 5, 4])

In [38]:
# Calcular la varianza de los tiempos de entrega

varianza_tiempos_entrega = np.var(tiempos_entrega)
varianza_tiempos_entrega.round(2)

np.float64(1.68)

 ### **<font color="DarkBlue">Desviación estándar</font>**

<p align="justify">
✅ La desviación estándar es la raíz cuadrada de la varianza. Proporciona una medida de dispersión en la misma unidad que los datos originales. Una desviación estándar alta indica que los datos están más dispersos.
<br><br>
  $$
  \text{Desviación Estándar} = \sqrt{\text{Varianza}}
  $$
<br>
👀 Por ejemplo, para calcular la desviación estándar de los precios de los productos en una tienda...


In [39]:
# Precios de los productos en una tienda en dólares

precios_productos = np.array([20, 25, 30, 35, 40, 35, 40, 20])
precios_productos

array([20, 25, 30, 35, 40, 35, 40, 20])

In [40]:
# Calcular la desviación estándar de los precios de los productos

desviacion_precios = np.std(precios_productos)
desviacion_precios.round(2)

np.float64(7.68)

<br>
<br>
<p align="center"><b>
💗
<font color="DarkBlue">
Hemos llegado al final de nuestro colab, a seguir codeando en NumPy...
</font>
</p>
